### PR TITLE
Add man page (5) for soscleaner.conf

### PR DESCRIPTION
**Pull request by slashdd**
Fix: #122

Signed-off-by: Eric Desrochers <eric.desrochers@canonical.com>

### CODE REVIEW

**Comment by slashdd** [comment]
Here's a first iteration of a `man 5 soscleaner.conf`

**Comment by slashdd** [comment]
man 5 soscleaner.conf
```
soscleaner.conf(5)                                                                        File Formats Manual                                                                       soscleaner.conf(5)

NAME
       soscleaner.conf - soscleaner configuration

DESCRIPTION
       soscleaner uses a configuration file at /etc/soscleaner.conf.

PARAMETERS
       There are five optionnal sections in the soscleaner configuration file: Default, DomainConfig, KeywordConfig, NetworkConfig and MacConfig.

       Some options accept a comma separated list of values.

EXAMPLES
       A sample config file:

       [Default]
       # The loglevel to run at, default is 'info'
       loglevel = debug
       # Domain to use for obfuscation
       root_domain = example.com
       # Defaults to False, True suppresses output to stdout
       quiet = True

       [DomainConfig]
       # Additional domains to obfuscate
       domains: example.com,foo.com,domain.com

       [KeywordConfig]
       # Keywords to obfuscate
       keywords: foo,bar,some,other,words
       # Keyword files to obfuscate
       keyword_files: keywords.txt

       [NetworkConfig]
       # Additional networks to obfuscate
       networks: 172.16.0.0/16

       [MacConfig]
       # True/False (defaults to True) - if False MAC obfuscation
       obfuscate_macs = False

FILES
       /etc/soscleaner.conf

SEE ALSO
       soscleaner(8)

soscleaner configuration file                                                                 SOSCLEANER                                                                            soscleaner.conf(5)

```

**Comment by slashdd** [comment]
This also assume that we go ahead with 'soscleaner.conf' (see issue #107) naming convention for all platform distribution.
Which I think would be the ideal, again just like sos.conf does.

**Comment by jduncan-rva** [comment]
[ci skip] at the end of a commit will prevent Travis CI from running for cosmetic changes and/or docs updates.

**Pull request merged**
